//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProjectImage
    {
        [Key]
        public int ImageID { get; set; }
        public int ProjectID { get; set; }
        public string ImageURL { get; set; }
        [Display(Name = "Description")]
        public string ImageDescription { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
