//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Project
    {
        [Key]
        public int ProjectId { get; set; }
        [Display(Name = "Name")]
        public string Name { get; set; }
        [Display(Name = "Description")]
        public string Description { get; set; }
        [Display(Name = "Preview Image")]
        public string ScreenshotURL { get; set; }
        [Display(Name = "Github Repo")]
        public string GithubURL { get; set; }
        [Display(Name = "Other Information")]
        public string OtherInfo { get; set; }
        [Display(Name = "Tools & Skills")]
        public string ToolsAndSkills { get; set; }
    }
}
